[package]
name = "amzn_fks2_lib"
version = "0.1.0"
edition = "2021"
publish = ["brazil"]
exclude = ['/build', '/Config', '/build-tools/']

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
